### ISSUE TITLE
Death by Snail (non-explosion at least) leads to game freezing until lobby restart.

### ISSUE THREAD

**Issue by VirusTLNR** [swAAn01/ImmortalSnail#1]
only happened a few times, not sure "explosion" death is fine either, and my group do run a heavy list of mods, but just thought id mention it.

I dont have logs sadly as this happened last weekend, and we turned the snail off to see if the issue stopped, and it did, so we didnt turn it back on, so its at least not a "death" related issue, and more likely a snail death related issue

**Comment by swAAn01** [comment]
2 Questions:

1. Are you using the most recent version of the mod? 0.7.3
2. Are you playing on v50?

I haven't tested this mod for v50 yet, so if that's what you were playing on, this may be the issue. It's also possible that there is a conflict with another mod. This is the first report I've seen of this, so if it happens again, I think seeing the logs would narrow-down the issue.

**Comment by Nekoaii** [comment]
LethalLib just got updated so it does work on v50 but I cant get the snail to kill people.

I get this ERROR when the snail touches me
 `[Error  : Unity Log] MissingMethodException: Method not found: void .Landmine.SpawnExplosion(UnityEngine.Vector3,bool,single,single)
Stack trace:
ImmortalSnail.SnailAI.KillPlayerServerRpc (System.Int32 playerId) (at <bcddb614b70c4ca5a4788c6a994ca273>:IL_00E3)
ImmortalSnail.SnailAI.OnCollideWithPlayer (UnityEngine.Collider other) (at <bcddb614b70c4ca5a4788c6a994ca273>:IL_0055)
EnemyAICollisionDetect.OnTriggerStay (UnityEngine.Collider other) (at <1ff0abda334d405f8f8b4762bb39ae86>:IL_0041)`

**Comment by swAAn01** [comment]
I looked into this, and it looks like it has to do with the `Landmine.SpawnExplosion` method in v50. Zeekerss must have fixed this, as in my recent testing there aren't any issues. At any rate, I've just published an update that seems to be fully functional on v50. Let me know if this issue persists!
